export const PROJECT_FORM = "PROJECT_FORM";
export const GET_ALLPROJECTS = "GET_ALLPROJECTS";
export const ADD_PROJECT = "ADD_ALLPROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const CURRENT_PROJECT = "CURRENT_PROJECT";