export const PROJECT_FORM = "PROJECT_FORM";
export const GET_ALLPROJECTS = "GET_ALLPROJECTS";
export const ADD_PROJECT = "ADD_ALLPROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const TASK_PER_PROJECT = "TASK_PER_PROJECT";
export const ADD_NEW_TASK = "ADD_NEW_TASK";